[project]
name = "walletconnectv4"
description = "Wallet Connect challenge Level 3"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.walletconnectv4]
path = "contracts/walletconnectv4.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
